server:
  port: 9091

spring:
  application:
    name: gateway
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    nacos:
      enabled: true
      discovery:
        server-addr: localhost:8848
        namespace: Acmsdy
    gateway:
      discovery:
          locator:
            enabled: false
      globalcors:
        cors-configurations:
          '[/**]': # 匹配所有请求
            allowedOrigins: "*" # 跨域处理 允许所有的域
            allowedMethods: # 支持的方法
              - GET
              - POST
              - PUT
              - DELETE
    sentinel:
      transport:
        dashboard: localhost:8080 #配置Sentinel dashboard地址
  main:
    web-application-type: reactive
feign:
 sentinel:
  enabled: true
gateway:
  routes:
    config:
      data-id: gateway-routes  #动态路由
      group: hospital
      namespace: Acmsdy



