server:
  port: 9092

spring:
  application:
    name: userService
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: Acmsdy
    sentinel:
      transport:
        dashboard: localhost:8080 #配置Sentinel dashboard地址
  datasource:
    url: jdbc:mysql://localhost:3306/hospital
    username: root
    password: 2895369781
    driver-class-name: com.mysql.cj.jdbc.Driver
# Mybatis log plugin 插件输出日志配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
feign:
  sentinel:
    enabled: true
